db.collection_name.find({})
db.restaurants.find({}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1})
db.restaurants.find({}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1, _id: 0})
db.restaurants.find({}, {restaurant_id: 1, name: 1, borough: 1, _id: 0, "address.zipcode": 1})
db.restaurants.find({borough: "Bronx"}, {grades: 0})
db.restaurants.find({borough: "Bronx"}, {grades: 0}).limit(5)
db.restaurants.find({borough: "Bronx"}, {grades: 0}).skip(5).limit(5)
db.restaurants.find({"grades.score": {$gt: 90}})
db.restaurants.find({"grades.score": {$gt: 80, $lt: 100}})
db.restaurants.find({"address.coord.0": {$lt: -95.754168}})
db.restaurants.find({cuisine: {$nin: ["American", "American "]}, "grades.score": {$gt: 70}, "address.coord.1": {$lt: -65.754168}}, {grades: 0})

db.restaurants.find({cuisine: {$nin: ["American", "American "]}, "grades.grade": "A", borough: {$ne: "Brooklyn"}}).sort({cuisine: -1})
db.restaurants.find({name: {$regex: /^Wil/i}}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1})
db.restaurants.find({name: {$regex: /ces$/i}}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1})
db.restaurants.find({name: {$regex: /Reg/i}}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1})
db.restaurants.find({borough: "Bronx", cuisine: {$in: ["American", "American ", "Chinese"]}}, {grades: 0})
db.restaurants.find({borough: {$in: ["Staten Island", "Queens", "Bronx", "Brooklyn"]}}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1})
db.restaurants.find({borough: {$nin: ["Staten Island", "Queens", "Bronx", "Brooklyn"]}}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1})
db.restaurants.find({"grades": {$elemMatch: {"score": {$lte: 10}}}}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1})
db.restaurants.find({$or: [{cuisine: "Fish", name: {$nin: ["American", "American ", "Chinese"]}}, {name: /^Wil/i}]}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1})
db.restaurants.find({"grades": {$elemMatch: {"grade": "A", "score": 11, "date": ISODate("2014-08-11T00:00:00Z")}}}, {restaurant_id: 1, name: 1, grades: 1})
db.restaurants.find({"grades.1.grade": "A", "grades.1.score": 9, "grades.1.date": ISODate("2014-08-11T00:00:00Z")}, {restaurant_id: 1, name: 1, grades: 1})
db.restaurants.find({"address.coord.1": {$gt: 42, $lt: 52}}, {restaurant_id: 1, name: 1, address: 1}, {"address.coord": 1})
db.restaurants.find({}, {grades: 0}).sort({name: 1})
db.restaurants.find({}, {grades: 0}).sort({name: -1})
db.restaurants.find().sort({cuisine: 1, borough: -1})
